export const emojis = [
        {"name": "Fish", "symbol": "🐟"},
        {"name": "Grinning Face", "symbol": "😀"},
        {"name": "Red Heart", "symbol": "❤️"},
        {"name": "Earth Globe", "symbol": "🌍"},
        {"name": "Cat Face", "symbol": "🐱"},
        {"name": "Glowing Star", "symbol": "🌟"},
        {"name": "Books", "symbol": "📚"},
        {"name": "Pizza", "symbol": "🍕"},
        {"name": "Rocket", "symbol": "🚀"},
        {"name": "Rainbow", "symbol": "🌈"},
        {"name": "Headphone", "symbol": "🎧"},
        {"name": "Face with Tears of Joy", "symbol": "😂"},
        {"name": "Face with Stuck-Out Tongue", "symbol": "😜"},
        {"name": "Rolling on the Floor & Laugh", "symbol": "🤣"},
        {"name": "Upside-Down Face", "symbol": "🙃"},
        {"name": "Zany Face", "symbol": "🤪"},
        {"name": "Cat Face with Tears of Joy", "symbol": "😹"},
        {"name": "Clown Face", "symbol": "🤡"},
        {"name": "Cowboy Hat Face", "symbol": "🤠"},
        {"name": "Smiling Face with Sunglasses", "symbol": "😎"},
        {"name": "Nerd Face", "symbol": "🤓"},
        {"name": "Fire", "symbol": "🔥"},
    ];
    
